-- AlterTable
ALTER TABLE `Airports` MODIFY `ident` VARCHAR(191) NULL,
    MODIFY `type` VARCHAR(191) NULL,
    MODIFY `name` VARCHAR(191) NULL,
    MODIFY `continent` VARCHAR(191) NULL,
    MODIFY `iso_country` VARCHAR(191) NULL,
    MODIFY `iso_region` VARCHAR(191) NULL,
    MODIFY `municipality` VARCHAR(191) NULL,
    MODIFY `scheduled_service` VARCHAR(191) NULL,
    MODIFY `gps_code` VARCHAR(191) NULL,
    MODIFY `iata_code` VARCHAR(191) NULL,
    MODIFY `local_code` VARCHAR(191) NULL,
    MODIFY `home_link` VARCHAR(191) NULL,
    MODIFY `wikipedia_link` VARCHAR(191) NULL,
    MODIFY `keywords` VARCHAR(191) NULL;
