INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302556, 'AO', 'Angola', 'AF', 'https://en.wikipedia.org/wiki/Angola', 'Angolan airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302557, 'BF', 'Burkina Faso', 'AF', 'https://en.wikipedia.org/wiki/Burkina_Faso', 'Burkinabé airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302558, 'BI', 'Burundi', 'AF', 'https://en.wikipedia.org/wiki/Burundi', 'Burundian airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302559, 'BJ', 'Benin', 'AF', 'https://en.wikipedia.org/wiki/Benin', 'Beninese airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302560, 'BW', 'Botswana', 'AF', 'https://en.wikipedia.org/wiki/Botswana', 'Botswana airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302561, 'CD', 'Democratic Republic of the Congo', 'AF', 'https://en.wikipedia.org/wiki/Democratic_Republic_of_the_Congo', 'DRC');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302562, 'CF', 'Central African Republic', 'AF', 'https://en.wikipedia.org/wiki/Central_African_Republic', 'Airports in Central African Republic');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302563, 'CG', 'Republic of the Congo', 'AF', 'https://en.wikipedia.org/wiki/Republic_of_the_Congo', 'Congo-Brazzaville');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302564, 'CI', 'Côte d\'Ivoire', 'AF', 'https://en.wikipedia.org/wiki/Côte_d\'Ivoire', 'Ivory Coast');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302565, 'CM', 'Cameroon', 'AF', 'https://en.wikipedia.org/wiki/Cameroon', 'Cameroonian airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302566, 'CV', 'Cape Verde', 'AF', 'https://en.wikipedia.org/wiki/Cape_Verde', 'Airports in Cape Verde');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302567, 'DJ', 'Djibouti', 'AF', 'https://en.wikipedia.org/wiki/Djibouti', 'Djiboutian airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302568, 'DZ', 'Algeria', 'AF', 'https://en.wikipedia.org/wiki/Algeria', 'مطارات الجزائر');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302569, 'EG', 'Egypt', 'AF', 'https://en.wikipedia.org/wiki/Egypt', 'مطارات مصر, Egyptian airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302570, 'EH', 'Western Sahara', 'AF', 'https://en.wikipedia.org/wiki/Western_Sahara', 'Sahrawian, مطارات الصحراء الغربية');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302571, 'ER', 'Eritrea', 'AF', 'https://en.wikipedia.org/wiki/Eritrea', 'Eritrean airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302572, 'ET', 'Ethiopia', 'AF', 'https://en.wikipedia.org/wiki/Ethiopia', 'Ethiopian airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302573, 'GA', 'Gabon', 'AF', 'https://en.wikipedia.org/wiki/Gabon', 'Gabonese airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302574, 'GH', 'Ghana', 'AF', 'https://en.wikipedia.org/wiki/Ghana', 'Ghanan airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302575, 'GM', 'Gambia', 'AF', 'https://en.wikipedia.org/wiki/Gambia', 'Gambian airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302576, 'GN', 'Guinea', 'AF', 'https://en.wikipedia.org/wiki/Guinea', 'Aéroports de la Guinée');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302577, 'GQ', 'Equatorial Guinea', 'AF', 'https://en.wikipedia.org/wiki/Equatorial_Guinea', 'Airports in Equatorial Guinea');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302578, 'GW', 'Guinea-Bissau', 'AF', 'https://en.wikipedia.org/wiki/Guinea-Bissau', 'Airports in Guinea-Bissau');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302579, 'KE', 'Kenya', 'AF', 'https://en.wikipedia.org/wiki/Kenya', 'Kenyan airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302580, 'KM', 'Comoros', 'AF', 'https://en.wikipedia.org/wiki/Comoros', 'جزر القمر');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302581, 'LR', 'Liberia', 'AF', 'https://en.wikipedia.org/wiki/Liberia', null);
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302582, 'LS', 'Lesotho', 'AF', 'https://en.wikipedia.org/wiki/Lesotho', 'Airports in Lesotho');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302583, 'LY', 'Libya', 'AF', 'https://en.wikipedia.org/wiki/Libya', 'مطارات في ليبيا');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302584, 'MA', 'Morocco', 'AF', 'https://en.wikipedia.org/wiki/Morocco', 'مطارات المغرب');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302585, 'MG', 'Madagascar', 'AF', 'https://en.wikipedia.org/wiki/Madagascar', 'Airports in Madagascar');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302586, 'ML', 'Mali', 'AF', 'https://en.wikipedia.org/wiki/Mali', 'Aéroports du Mali, Malian airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302587, 'MR', 'Mauritania', 'AF', 'https://en.wikipedia.org/wiki/Mauritania', 'مطارات موريتانيا');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302588, 'MU', 'Mauritius', 'AF', 'https://en.wikipedia.org/wiki/Mauritius', 'Airports in Mauritius');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302589, 'MW', 'Malawi', 'AF', 'https://en.wikipedia.org/wiki/Malawi', 'Airports in Malawi');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302590, 'MZ', 'Mozambique', 'AF', 'https://en.wikipedia.org/wiki/Mozambique', 'Airports in Mozambique');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302591, 'NA', 'Namibia', 'AF', 'https://en.wikipedia.org/wiki/Namibia', null);
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302592, 'NE', 'Niger', 'AF', 'https://en.wikipedia.org/wiki/Niger', 'Nigerien airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302593, 'NG', 'Nigeria', 'AF', 'https://en.wikipedia.org/wiki/Nigeria', null);
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302594, 'RE', 'Réunion', 'AF', 'https://en.wikipedia.org/wiki/Réunion', 'Île Bourbon, La Réunion');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302595, 'RW', 'Rwanda', 'AF', 'https://en.wikipedia.org/wiki/Rwanda', null);
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302596, 'SC', 'Seychelles', 'AF', 'https://en.wikipedia.org/wiki/Seychelles', 'Airports in Seychelles');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302597, 'SD', 'Sudan', 'AF', 'https://en.wikipedia.org/wiki/Sudan', 'مطارات السودان');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302598, 'SH', 'Saint Helena, Ascension and Tristan da Cunha', 'AF', 'https://en.wikipedia.org/wiki/Saint_Helena,_Ascension_and_Tristan_da_Cunha', 'Airports in Saint Helena, Ascension and Tristan da Cunha');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302599, 'SL', 'Sierra Leone', 'AF', 'https://en.wikipedia.org/wiki/Sierra_Leone', 'Sierra Leonean airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302600, 'SN', 'Senegal', 'AF', 'https://en.wikipedia.org/wiki/Senegal', 'Aéroports du Sénégal, Senegalese airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302601, 'SO', 'Somalia', 'AF', 'https://en.wikipedia.org/wiki/Somalia', null);
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302602, 'ST', 'São Tomé and Principe', 'AF', 'https://en.wikipedia.org/wiki/São_Tomé_and_Principe', 'Airports in São Tomé and Principe');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302603, 'SZ', 'Eswatini', 'AF', 'https://en.wikipedia.org/wiki/Eswatini', 'Swaziland');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302604, 'TD', 'Chad', 'AF', 'https://en.wikipedia.org/wiki/Chad', 'Airports in Chad');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302605, 'TG', 'Togo', 'AF', 'https://en.wikipedia.org/wiki/Togo', 'Airports in Togo');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302606, 'TN', 'Tunisia', 'AF', 'https://en.wikipedia.org/wiki/Tunisia', 'مطارات تونس');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302607, 'TZ', 'Tanzania', 'AF', 'https://en.wikipedia.org/wiki/Tanzania', 'Tanzanian airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302608, 'UG', 'Uganda', 'AF', 'https://en.wikipedia.org/wiki/Uganda', null);
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302609, 'YT', 'Mayotte', 'AF', 'https://en.wikipedia.org/wiki/Mayotte', 'Airports in Mayotte');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302610, 'ZA', 'South Africa', 'AF', 'https://en.wikipedia.org/wiki/South_Africa', 'South African airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302611, 'ZM', 'Zambia', 'AF', 'https://en.wikipedia.org/wiki/Zambia', 'Zambian airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302612, 'ZW', 'Zimbabwe', 'AF', 'https://en.wikipedia.org/wiki/Zimbabwe', 'Zimbabwan airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302613, 'ZZ', 'Unknown or unassigned country', 'AF', 'https://en.wikipedia.org/wiki/Unknown_or_unassigned_country', 'Airports in Unknown or unassigned country');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302614, 'SS', 'South Sudan', 'AF', 'https://en.wikipedia.org/wiki/South_Sudan', 'South Sudanese airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302615, 'AQ', 'Antarctica', 'AN', 'https://en.wikipedia.org/wiki/Antarctica', 'Airports in Antarctica');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302616, 'GS', 'South Georgia and the South Sandwich Islands', 'AN', 'https://en.wikipedia.org/wiki/South_Georgia_and_the_South_Sandwich_Islands', 'Airports in South Georgia and the South Sandwich Islands');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302617, 'TF', 'French Southern and Antarctic Lands', 'AF', 'https://en.wikipedia.org/wiki/French_Southern_and_Antarctic_Lands', 'Airports in French Southern and Antarctic Lands');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302618, 'AE', 'United Arab Emirates', 'AS', 'https://en.wikipedia.org/wiki/United_Arab_Emirates', 'UAE,مطارات في الإمارات العربية المتحدة');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302619, 'AF', 'Afghanistan', 'AS', 'https://en.wikipedia.org/wiki/Afghanistan', null);
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302620, 'AM', 'Armenia', 'AS', 'https://en.wikipedia.org/wiki/Armenia', null);
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302621, 'AZ', 'Azerbaijan', 'AS', 'https://en.wikipedia.org/wiki/Azerbaijan', 'Azerbaijani airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302622, 'BD', 'Bangladesh', 'AS', 'https://en.wikipedia.org/wiki/Bangladesh', 'Bangladeshi airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302623, 'BH', 'Bahrain', 'AS', 'https://en.wikipedia.org/wiki/Bahrain', 'مطارات البحرين');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302624, 'BN', 'Brunei', 'AS', 'https://en.wikipedia.org/wiki/Brunei', 'Bruneian airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302625, 'BT', 'Bhutan', 'AS', 'https://en.wikipedia.org/wiki/Bhutan', 'Bhutanese airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302626, 'CC', 'Cocos (Keeling) Islands', 'AS', 'https://en.wikipedia.org/wiki/Cocos_(Keeling)_Islands', 'Airports in Cocos (Keeling) Islands');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302627, 'CN', 'China', 'AS', 'https://en.wikipedia.org/wiki/China', '中国的机场');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302628, 'CX', 'Christmas Island', 'AS', 'https://en.wikipedia.org/wiki/Christmas_Island', 'Airports in Christmas Island');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302629, 'CY', 'Cyprus', 'AS', 'https://en.wikipedia.org/wiki/Cyprus', 'Cypriot airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302630, 'GE', 'Georgia', 'AS', 'https://en.wikipedia.org/wiki/Georgia_(country)', 'Georgian airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302631, 'HK', 'Hong Kong', 'AS', 'https://en.wikipedia.org/wiki/Hong_Kong', 'Airports in Hong Kong');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302632, 'ID', 'Indonesia', 'AS', 'https://en.wikipedia.org/wiki/Indonesia', 'Bandara di Indonesia');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302633, 'IL', 'Israel', 'AS', 'https://en.wikipedia.org/wiki/Israel', 'שדות התעופה של ישראל');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302634, 'IN', 'India', 'AS', 'https://en.wikipedia.org/wiki/India', 'Airports in India, Indian airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302635, 'IO', 'British Indian Ocean Territory', 'AS', 'https://en.wikipedia.org/wiki/British_Indian_Ocean_Territory', 'Airports in British Indian Ocean Territory');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302636, 'IQ', 'Iraq', 'AS', 'https://en.wikipedia.org/wiki/Iraq', 'مطارات العراق');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302637, 'IR', 'Iran', 'AS', 'https://en.wikipedia.org/wiki/Iran', 'فرودگاه های ایران');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302638, 'JO', 'Jordan', 'AS', 'https://en.wikipedia.org/wiki/Jordan', 'مطارات في الأردن');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302639, 'JP', 'Japan', 'AS', 'https://en.wikipedia.org/wiki/Japan', 'Nippon, 日本の空港');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302640, 'KG', 'Kyrgyzstan', 'AS', 'https://en.wikipedia.org/wiki/Kyrgyzstan', null);
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302641, 'KH', 'Cambodia', 'AS', 'https://en.wikipedia.org/wiki/Cambodia', 'Cambodian airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302642, 'KP', 'North Korea', 'AS', 'https://en.wikipedia.org/wiki/North_Korea', 'North Korean airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302643, 'KR', 'South Korea', 'AS', 'https://en.wikipedia.org/wiki/South_Korea', '한국의 공항');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302644, 'KW', 'Kuwait', 'AS', 'https://en.wikipedia.org/wiki/Kuwait', 'Kuwaiti airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302645, 'KZ', 'Kazakhstan', 'AS', 'https://en.wikipedia.org/wiki/Kazakhstan', 'Kazakh');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302646, 'LA', 'Laos', 'AS', 'https://en.wikipedia.org/wiki/Laos', 'Laotian airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302647, 'LB', 'Lebanon', 'AS', 'https://en.wikipedia.org/wiki/Lebanon', 'المطارات في لبنان');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302648, 'LK', 'Sri Lanka', 'AS', 'https://en.wikipedia.org/wiki/Sri_Lanka', 'Sri Lankan airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302649, 'MM', 'Myanmar', 'AS', 'https://en.wikipedia.org/wiki/Burma', 'Myanmar');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302650, 'MN', 'Mongolia', 'AS', 'https://en.wikipedia.org/wiki/Mongolia', 'Mongolian airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302651, 'MO', 'Macau', 'AS', 'https://en.wikipedia.org/wiki/Macau', 'Macao');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302652, 'MV', 'Maldives', 'AS', 'https://en.wikipedia.org/wiki/Maldives', 'Airports in Maldives');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302653, 'MY', 'Malaysia', 'AS', 'https://en.wikipedia.org/wiki/Malaysia', 'Lapangan Terbang Malaysia');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302654, 'NP', 'Nepal', 'AS', 'https://en.wikipedia.org/wiki/Nepal', 'नेपाल विमानस्थलको');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302655, 'OM', 'Oman', 'AS', 'https://en.wikipedia.org/wiki/Oman', 'مطارات عمان');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302656, 'PH', 'Philippines', 'AS', 'https://en.wikipedia.org/wiki/Philippines', 'Mga alternatibong byahe mula sa Pilipinas');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302657, 'PK', 'Pakistan', 'AS', 'https://en.wikipedia.org/wiki/Pakistan', 'پاکستان کے ہوائی اڈوں');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302658, 'PS', 'Palestinian Territory', 'AS', 'https://en.wikipedia.org/wiki/Palestinian_Territory', 'Palestinian airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302659, 'QA', 'Qatar', 'AS', 'https://en.wikipedia.org/wiki/Qatar', 'مطارات قطر');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302660, 'SA', 'Saudi Arabia', 'AS', 'https://en.wikipedia.org/wiki/Saudi_Arabia', 'مطارات المملكة العربية السعودية,المطارات لموسم الحج');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302661, 'SG', 'Singapore', 'AS', 'https://en.wikipedia.org/wiki/Singapore', 'Singaporean airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302662, 'SY', 'Syria', 'AS', 'https://en.wikipedia.org/wiki/Syria', 'مطارات سوريا');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302663, 'TH', 'Thailand', 'AS', 'https://en.wikipedia.org/wiki/Thailand', 'Siam, Siamese');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302664, 'TJ', 'Tajikistan', 'AS', 'https://en.wikipedia.org/wiki/Tajikistan', 'Tajik');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302665, 'TL', 'Timor-Leste', 'AS', 'https://en.wikipedia.org/wiki/Timor-Leste', 'East Timor');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302666, 'TM', 'Turkmenistan', 'AS', 'https://en.wikipedia.org/wiki/Turkmenistan', 'Turkmenistani airports, Airports in Turkmenistan');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302667, 'TR', 'Turkey', 'AS', 'https://en.wikipedia.org/wiki/Turkey', 'Türkiye havaalanları');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302668, 'TW', 'Taiwan', 'AS', 'https://en.wikipedia.org/wiki/Taiwan', 'Taiwanese airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302669, 'UZ', 'Uzbekistan', 'AS', 'https://en.wikipedia.org/wiki/Uzbekistan', 'Uzbek');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302670, 'VN', 'Vietnam', 'AS', 'https://en.wikipedia.org/wiki/Vietnam', 'Các sân bay của Việt Nam');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302671, 'YE', 'Yemen', 'AS', 'https://en.wikipedia.org/wiki/Yemen', 'مطارات اليمن');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302672, 'AD', 'Andorra', 'EU', 'https://en.wikipedia.org/wiki/Andorra', 'Andorran airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302673, 'AL', 'Albania', 'EU', 'https://en.wikipedia.org/wiki/Albania', 'Albanian airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302674, 'AT', 'Austria', 'EU', 'https://en.wikipedia.org/wiki/Austria', 'Flughäfen in Österreich');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302675, 'BA', 'Bosnia and Herzegovina', 'EU', 'https://en.wikipedia.org/wiki/Bosnia_and_Herzegovina', 'Bosnian airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302676, 'BE', 'Belgium', 'EU', 'https://en.wikipedia.org/wiki/Belgium', 'Aéroports de Belgique,Luchthavens van België');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302677, 'BG', 'Bulgaria', 'EU', 'https://en.wikipedia.org/wiki/Bulgaria', 'Bulgarian airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302678, 'BY', 'Belarus', 'EU', 'https://en.wikipedia.org/wiki/Belarus', 'Belarussian, Беларусь');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302679, 'CH', 'Switzerland', 'EU', 'https://en.wikipedia.org/wiki/Switzerland', 'Aéroports de la Suisse,Flughäfen der Schweiz');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302680, 'CZ', 'Czech Republic', 'EU', 'https://en.wikipedia.org/wiki/Czech_Republic', 'Letiště České republiky, Czechia');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302681, 'DE', 'Germany', 'EU', 'https://en.wikipedia.org/wiki/Germany', 'Flughäfen in Deutschland');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302682, 'DK', 'Denmark', 'EU', 'https://en.wikipedia.org/wiki/Denmark', 'Lufthavnene i Danmark');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302683, 'EE', 'Estonia', 'EU', 'https://en.wikipedia.org/wiki/Estonia', 'Estonian airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302684, 'ES', 'Spain', 'EU', 'https://en.wikipedia.org/wiki/Spain', 'Aeropuertos de España');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302685, 'FI', 'Finland', 'EU', 'https://en.wikipedia.org/wiki/Finland', 'Lentokentät, Suomen');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302686, 'FO', 'Faroe Islands', 'EU', 'https://en.wikipedia.org/wiki/Faroe_Islands', 'Faroese airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302687, 'FR', 'France', 'EU', 'https://en.wikipedia.org/wiki/France', 'Aéroports de France');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302688, 'GB', 'United Kingdom', 'EU', 'https://en.wikipedia.org/wiki/United_Kingdom', 'Great Britain');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302689, 'GG', 'Guernsey', 'EU', 'https://en.wikipedia.org/wiki/Guernsey', 'Airports in Guernsey');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302690, 'GI', 'Gibraltar', 'EU', 'https://en.wikipedia.org/wiki/Gibraltar', 'Gibraltarian airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302691, 'GR', 'Greece', 'EU', 'https://en.wikipedia.org/wiki/Greece', 'αεροδρόμια στην Ελλάδα');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302692, 'HR', 'Croatia', 'EU', 'https://en.wikipedia.org/wiki/Croatia', 'Croatian airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302693, 'HU', 'Hungary', 'EU', 'https://en.wikipedia.org/wiki/Hungary', 'Repülőterek Magyarország');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302694, 'IE', 'Ireland', 'EU', 'https://en.wikipedia.org/wiki/Ireland', 'Eire');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302695, 'IM', 'Isle of Man', 'EU', 'https://en.wikipedia.org/wiki/Isle_of_Man', 'Manx');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302696, 'IS', 'Iceland', 'EU', 'https://en.wikipedia.org/wiki/Iceland', 'Icelandic airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302697, 'IT', 'Italy', 'EU', 'https://en.wikipedia.org/wiki/Italy', 'Aeroporti d\'Italia');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302698, 'JE', 'Jersey', 'EU', 'https://en.wikipedia.org/wiki/Jersey', 'Airports in Jersey');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302699, 'LI', 'Liechtenstein', 'EU', 'https://en.wikipedia.org/wiki/Liechtenstein', 'Airports in Liechtenstein');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302700, 'LT', 'Lithuania', 'EU', 'https://en.wikipedia.org/wiki/Lithuania', 'Lithuanian airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302701, 'LU', 'Luxembourg', 'EU', 'https://en.wikipedia.org/wiki/Luxembourg', 'Airports in Luxembourg');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302702, 'LV', 'Latvia', 'EU', 'https://en.wikipedia.org/wiki/Latvia', 'Latvian airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302703, 'MC', 'Monaco', 'EU', 'https://en.wikipedia.org/wiki/Monaco', 'Airports in Monaco');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302704, 'MD', 'Moldova', 'EU', 'https://en.wikipedia.org/wiki/Moldova', 'Airports in Moldova');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302705, 'ME', 'Montenegro', 'EU', 'https://en.wikipedia.org/wiki/Montenegro', 'Montenegran airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302706, 'MK', 'North Macedonia', 'EU', 'https://en.wikipedia.org/wiki/Macedonia', 'Macedonian airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302707, 'MT', 'Malta', 'EU', 'https://en.wikipedia.org/wiki/Malta', null);
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302708, 'NL', 'Netherlands', 'EU', 'https://en.wikipedia.org/wiki/Netherlands', 'Holland, Luchthavens van Nederland, Dutch airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302709, 'NO', 'Norway', 'EU', 'https://en.wikipedia.org/wiki/Norway', 'Flyplasser i Norge');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302710, 'PL', 'Poland', 'EU', 'https://en.wikipedia.org/wiki/Poland', 'Lotniska Polski');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302711, 'PT', 'Portugal', 'EU', 'https://en.wikipedia.org/wiki/Portugal', 'Aeroportos de Portugal');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302712, 'RO', 'Romania', 'EU', 'https://en.wikipedia.org/wiki/Romania', 'Aeroporturi din România');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302713, 'RS', 'Serbia', 'EU', 'https://en.wikipedia.org/wiki/Serbia', 'Serb');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302714, 'RU', 'Russia', 'EU', 'https://en.wikipedia.org/wiki/Russia', 'Soviet, Sovietskaya, Sovetskaya, Аэропорты России');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302715, 'SE', 'Sweden', 'EU', 'https://en.wikipedia.org/wiki/Sweden', 'Flygplatserna, Sverige');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302716, 'SI', 'Slovenia', 'EU', 'https://en.wikipedia.org/wiki/Slovenia', null);
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302717, 'SK', 'Slovakia', 'EU', 'https://en.wikipedia.org/wiki/Slovakia', 'letisko Slovenska');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302718, 'SM', 'San Marino', 'EU', 'https://en.wikipedia.org/wiki/San_Marino', 'Airports in San Marino');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302719, 'UA', 'Ukraine', 'EU', 'https://en.wikipedia.org/wiki/Ukraine', 'Аеропорти України');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302720, 'XK', 'Kosovo', 'EU', 'https://en.wikipedia.org/wiki/Kosovo', 'Kosova');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302721, 'VA', 'Vatican City', 'EU', 'https://en.wikipedia.org/wiki/Vatican_City', 'The Holy See');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302722, 'AG', 'Antigua and Barbuda', 'NA', 'https://en.wikipedia.org/wiki/Antigua_and_Barbuda', 'Antiguan airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302723, 'AI', 'Anguilla', 'NA', 'https://en.wikipedia.org/wiki/Anguilla', null);
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302724, 'BQ', 'Caribbean Netherlands', 'NA', 'https://en.wikipedia.org/wiki/Caribbean_Netherlands', 'Airports in Caribbean Netherlands');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302725, 'AW', 'Aruba', 'NA', 'https://en.wikipedia.org/wiki/Aruba', null);
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302726, 'BB', 'Barbados', 'NA', 'https://en.wikipedia.org/wiki/Barbados', 'Barbadan airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302727, 'BM', 'Bermuda', 'NA', 'https://en.wikipedia.org/wiki/Bermuda', null);
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302728, 'BS', 'Bahamas', 'NA', 'https://en.wikipedia.org/wiki/Bahamas', 'Bahaman airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302729, 'BZ', 'Belize', 'NA', 'https://en.wikipedia.org/wiki/Belize', 'Belizean airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302730, 'CA', 'Canada', 'NA', 'https://en.wikipedia.org/wiki/Canada', 'Canadian airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302731, 'CR', 'Costa Rica', 'NA', 'https://en.wikipedia.org/wiki/Costa_Rica', 'Aeropuertos de Costa Rica');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302732, 'CU', 'Cuba', 'NA', 'https://en.wikipedia.org/wiki/Cuba', 'Aeropuertos de Cuba');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302733, 'DM', 'Dominica', 'NA', 'https://en.wikipedia.org/wiki/Dominica', 'Airports in Dominica');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302734, 'DO', 'Dominican Republic', 'NA', 'https://en.wikipedia.org/wiki/Dominican_Republic', 'Airports in Dominican Republic');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302735, 'GD', 'Grenada', 'NA', 'https://en.wikipedia.org/wiki/Grenada', 'Grenadian airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302736, 'GL', 'Greenland', 'NA', 'https://en.wikipedia.org/wiki/Greenland', 'Airports in Greenland');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302737, 'GP', 'Guadeloupe', 'NA', 'https://en.wikipedia.org/wiki/Guadeloupe', 'Airports in Guadeloupe');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302738, 'GT', 'Guatemala', 'NA', 'https://en.wikipedia.org/wiki/Guatemala', 'Aeropuertos de Guatemala');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302739, 'HN', 'Honduras', 'NA', 'https://en.wikipedia.org/wiki/Honduras', 'Aeropuertos de Honduras');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302740, 'HT', 'Haiti', 'NA', 'https://en.wikipedia.org/wiki/Haiti', 'Aéroports de Haïti');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302741, 'JM', 'Jamaica', 'NA', 'https://en.wikipedia.org/wiki/Jamaica', 'Jamaican airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302742, 'KN', 'Saint Kitts and Nevis', 'NA', 'https://en.wikipedia.org/wiki/Saint_Kitts_and_Nevis', 'Airports in Saint Kitts and Nevis');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302743, 'KY', 'Cayman Islands', 'NA', 'https://en.wikipedia.org/wiki/Cayman_Islands', 'Airports in Cayman Islands');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302744, 'LC', 'Saint Lucia', 'NA', 'https://en.wikipedia.org/wiki/Saint_Lucia', 'Airports in Saint Lucia');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302745, 'MQ', 'Martinique', 'NA', 'https://en.wikipedia.org/wiki/Martinique', 'Airports in Martinique');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302746, 'MS', 'Montserrat', 'NA', 'https://en.wikipedia.org/wiki/Montserrat', 'Airports in Montserrat');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302747, 'MX', 'Mexico', 'NA', 'https://en.wikipedia.org/wiki/Mexico', 'Aeropuertos de México, Mexican airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302748, 'NI', 'Nicaragua', 'NA', 'https://en.wikipedia.org/wiki/Nicaragua', 'Aeropuertos de Nicaragua');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302749, 'PA', 'Panama', 'NA', 'https://en.wikipedia.org/wiki/Panama', 'Aeropuertos de Panamá');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302750, 'PM', 'Saint Pierre and Miquelon', 'NA', 'https://en.wikipedia.org/wiki/Saint_Pierre_and_Miquelon', 'Airports in Saint Pierre and Miquelon');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302751, 'PR', 'Puerto Rico', 'NA', 'https://en.wikipedia.org/wiki/Puerto_Rico', null);
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302752, 'SV', 'El Salvador', 'NA', 'https://en.wikipedia.org/wiki/El_Salvador', 'Salvadorian, Salvadorean');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302753, 'TC', 'Turks and Caicos Islands', 'NA', 'https://en.wikipedia.org/wiki/Turks_and_Caicos_Islands', 'Airports in Turks and Caicos Islands');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302754, 'TT', 'Trinidad and Tobago', 'NA', 'https://en.wikipedia.org/wiki/Trinidad_and_Tobago', 'Airports in Trinidad and Tobago');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302755, 'US', 'United States', 'NA', 'https://en.wikipedia.org/wiki/United_States', 'American airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302756, 'VC', 'Saint Vincent and the Grenadines', 'NA', 'https://en.wikipedia.org/wiki/Saint_Vincent_and_the_Grenadines', 'Airports in Saint Vincent and the Grenadines');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302757, 'VG', 'British Virgin Islands', 'NA', 'https://en.wikipedia.org/wiki/British_Virgin_Islands', 'Airports in British Virgin Islands');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302758, 'VI', 'U.S. Virgin Islands', 'NA', 'https://en.wikipedia.org/wiki/U.S._Virgin_Islands', 'Airports in U.S. Virgin Islands');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302759, 'MF', 'Saint Martin', 'NA', 'https://en.wikipedia.org/wiki/Saint_Martin_(France)', 'Airports in Saint Martin');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302760, 'BL', 'Saint Barthélemy', 'NA', 'https://en.wikipedia.org/wiki/Saint_Barthélemy', 'Airports in Saint Barthélemy');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302761, 'SX', 'Sint Maarten', 'NA', 'https://en.wikipedia.org/wiki/Sint_Maarten', 'Airports in Sint Maarten');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302762, 'CW', 'Curaçao', 'NA', 'https://en.wikipedia.org/wiki/Cura%C3%A7ao', 'Airports in Curaçao');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302763, 'AS', 'American Samoa', 'OC', 'https://en.wikipedia.org/wiki/American_Samoa', 'Samoan airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302764, 'AU', 'Australia', 'OC', 'https://en.wikipedia.org/wiki/Australia', 'Australian airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302765, 'CK', 'Cook Islands', 'OC', 'https://en.wikipedia.org/wiki/Cook_Islands', 'Airports in Cook Islands');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302766, 'FJ', 'Fiji', 'OC', 'https://en.wikipedia.org/wiki/Fiji', 'Fijan airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302767, 'FM', 'Micronesia', 'OC', 'https://en.wikipedia.org/wiki/Federated_States_of_Micronesia', 'Micronesian airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302768, 'GU', 'Guam', 'OC', 'https://en.wikipedia.org/wiki/Guam', 'Guamanian airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302769, 'KI', 'Kiribati', 'OC', 'https://en.wikipedia.org/wiki/Kiribati', 'Airports in Kiribati');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302770, 'MH', 'Marshall Islands', 'OC', 'https://en.wikipedia.org/wiki/Marshall_Islands', 'Airports in Marshall Islands');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302771, 'MP', 'Northern Mariana Islands', 'OC', 'https://en.wikipedia.org/wiki/Northern_Mariana_Islands', 'Airports in Northern Mariana Islands');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302772, 'NC', 'New Caledonia', 'OC', 'https://en.wikipedia.org/wiki/New_Caledonia', 'Airports in New Caledonia');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302773, 'NF', 'Norfolk Island', 'OC', 'https://en.wikipedia.org/wiki/Norfolk_Island', 'Airports in Norfolk Island');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302774, 'NR', 'Nauru', 'OC', 'https://en.wikipedia.org/wiki/Nauru', 'Airports in Nauru');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302775, 'NU', 'Niue', 'OC', 'https://en.wikipedia.org/wiki/Niue', 'Niuean airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302776, 'NZ', 'New Zealand', 'OC', 'https://en.wikipedia.org/wiki/New_Zealand', 'Airports in New Zealand');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302777, 'PF', 'French Polynesia', 'OC', 'https://en.wikipedia.org/wiki/French_Polynesia', null);
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302778, 'PG', 'Papua New Guinea', 'OC', 'https://en.wikipedia.org/wiki/Papua_New_Guinea', 'Airports in Papua New Guinea');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302779, 'PN', 'Pitcairn', 'OC', 'https://en.wikipedia.org/wiki/Pitcairn', 'Airports in Pitcairn');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302780, 'PW', 'Palau', 'OC', 'https://en.wikipedia.org/wiki/Palau', 'Palauan airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302781, 'SB', 'Solomon Islands', 'OC', 'https://en.wikipedia.org/wiki/Solomon_Islands', 'Airports in Solomon Islands');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302782, 'TK', 'Tokelau', 'OC', 'https://en.wikipedia.org/wiki/Tokelau', 'Airports in Tokelau');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302783, 'TO', 'Tonga', 'OC', 'https://en.wikipedia.org/wiki/Tonga', 'Airports in Tonga');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302784, 'TV', 'Tuvalu', 'OC', 'https://en.wikipedia.org/wiki/Tuvalu', 'Airports in Tuvalu');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302785, 'UM', 'United States Minor Outlying Islands', 'OC', 'https://en.wikipedia.org/wiki/United_States_Minor_Outlying_Islands', 'Airports in United States Minor Outlying Islands');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302786, 'VU', 'Vanuatu', 'OC', 'https://en.wikipedia.org/wiki/Vanuatu', 'Airports in Vanuatu');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302787, 'WF', 'Wallis and Futuna', 'OC', 'https://en.wikipedia.org/wiki/Wallis_and_Futuna', 'Airports in Wallis and Futuna');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302788, 'WS', 'Samoa', 'OC', 'https://en.wikipedia.org/wiki/Samoa', 'Samoan airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302789, 'AR', 'Argentina', 'SA', 'https://en.wikipedia.org/wiki/Argentina', 'Aeropuertos de Argentina');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302790, 'BO', 'Bolivia', 'SA', 'https://en.wikipedia.org/wiki/Bolivia', 'Aeropuertos de Bolivia');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302791, 'BR', 'Brazil', 'SA', 'https://en.wikipedia.org/wiki/Brazil', 'Brasil, Brasilian, Aeroportos do Brasil');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302792, 'CL', 'Chile', 'SA', 'https://en.wikipedia.org/wiki/Chile', 'Aeropuertos de Chile');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302793, 'CO', 'Colombia', 'SA', 'https://en.wikipedia.org/wiki/Colombia', 'Aeropuertos de Colombia');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302794, 'EC', 'Ecuador', 'SA', 'https://en.wikipedia.org/wiki/Ecuador', 'Aeropuertos de Ecuador');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302795, 'FK', 'Falkland Islands', 'SA', 'https://en.wikipedia.org/wiki/Falkland_Islands', 'Airports in Falkland Islands');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302796, 'GF', 'French Guiana', 'SA', 'https://en.wikipedia.org/wiki/French_Guiana', 'French Guyana');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302797, 'GY', 'Guyana', 'SA', 'https://en.wikipedia.org/wiki/Guyana', 'Guyanese airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302798, 'PE', 'Peru', 'SA', 'https://en.wikipedia.org/wiki/Perú', 'Aeropuertos de Perú');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302799, 'PY', 'Paraguay', 'SA', 'https://en.wikipedia.org/wiki/Paraguay', 'Aeropuertos de Paraguay');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302800, 'SR', 'Suriname', 'SA', 'https://en.wikipedia.org/wiki/Suriname', 'Surinamese airports');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302801, 'UY', 'Uruguay', 'SA', 'https://en.wikipedia.org/wiki/Uruguay', 'Aeropuertos de Uruguay');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (302802, 'VE', 'Venezuela', 'SA', 'https://en.wikipedia.org/wiki/Venezuela', 'Aeropuertos de Venezuela');
INSERT INTO jerryhobby.Countries (id, code, name, continent, wikipedia_link, keywords) VALUES (350209, 'HM', 'Heard and McDonald Islands', 'OC', 'https://en.wikipedia.org/wiki/Heard_Island_and_McDonald_Islands', 'Airports in Heard and McDonald Islands');
